### ISSUE TITLE
RTMP_Connect0, failed to connect socket. 111 (Connection refused)

### ISSUE THREAD

**Issue by wangluolaowu** [DevoutPrayer/streamer#2]
您好，根据你的提示；我在命令后面加入rtsp地址，其中192.168.1.12是rk3399地址，请问rtmp流地址是这样配置的吗？ 
另：我把存储的h264文件通过vlc播放器可以正常播放；我rk3399上连接的是一个usb摄像头；
端口号：1935我通过命令<sudo iptables -I INPUT -p tcp --dport 1935 -j ACCEPT>已经开启；

在rk3399上运行命令如下：
root@robot:/home/robot/project# ./stream_mpp rtmp://192.168.1.12:1935/live/room1
0: Motion-JPEG
1: YUYV 4:2:2
fmt.w=640,fmt.h=480
fmt.pixfmt=0x56595559
mpp[2519]: mpp_rt: NOT found ion allocator
mpp[2519]: mpp_rt: found drm allocator
mpp[2519]: mpp_info: mpp version: a86f586 author: Herman Chen    2021-02-07 [mpp_enc]: Fix crash on low frame rate case
mpp[2519]: h264e_api_v2: MPP_ENC_SET_PREP_CFG w:h [640:480] stride [640:480]
mpp[2519]: mpp_enc: send header for codec/prep cfg change
mpp[2519]: mpp_enc: mode cbr bps [1500000:2000000:2500000] fps fix [30/1] -> fix [30/1] gop i [60] v [0]
mpp[2519]: mpp_enc: MPP_ENC_SET_RC_CFG bps 2304000 [2160000 : 2448000] fps [30:30] gop 60
mpp[2519]: mpp_enc: send header for rc cfg change rc_mode/fps/gop
mpp[2519]: mpp_enc: mode vbr bps [2160000:2304000:2448000] fps fix [30/1] -> fix [30/1] gop i [60] v [0]
mpp[2519]: mpp_enc: send header for codec/prep cfg change
mpp[2519]: mpp_enc: Please use MPP_ENC_GET_HDR_SYNC instead of unsafe MPP_ENC_GET_EXTRA_INFO
mpp[2519]: mpp_enc: NOTE: MPP_ENC_GET_HDR_SYNC needs MppPacket input
mpp[2519]: vepu_common: warning: stride by bytes 640 is smarller than width 640 mutiple by pixel size 2
mpp[2519]: vepu_common: multiple stride 640 by pixel size 2 and set new byte stride to 1280
encoded frame 0 size 205648
encoded frame 1 size 186380
encoded frame 2 size 182878
encoded frame 3 size 181734
encoded frame 4 size 185204
encoded frame 5 size 181633
encoded frame 6 size 182427
encoded frame 7 size 182099
encoded frame 8 size 181454
encoded frame 9 size 182442
encoded frame 10 size 183748
encoded frame 11 size 182845
encoded frame 12 size 181860
encoded frame 13 size 181924
encoded frame 14 size 182934
encoded frame 15 size 181678
encoded frame 16 size 183626
encoded frame 17 size 181932
encoded frame 18 size 181612
encoded frame 19 size 183311
encoded frame 20 size 184529
encoded frame 21 size 181725
encoded frame 22 size 182145
encoded frame 23 size 185333
encoded frame 24 size 184049
encoded frame 25 size 182988
encoded frame 26 size 182302
encoded frame 27 size 183005
encoded frame 28 size 183524
encoded frame 29 size 184953
[h264 @ 0x24e9aa00] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, h264, from '/home/robot/project/output.h264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 640x480, 30 fps, 30 tbr, 1200k tbn, 60 tbc
Output #0, flv, to 'rtmp://192.168.1.12:1935/live/room1':
    Stream #0:0: Video: h264, yuv420p, 640x480, q=2-31, 60 tbc
RTMP_Connect0, failed to connect socket. 111 (Connection refused)
encode max 30 framesCould not open output URL 'rtmp://192.168.1.12:1935/live/room1'Error occurred.
Segmentation fault (core dumped)

另：我在命令后面把rtsp地址修改为我笔记本IP（192.168.1.14），报的错误一样；
笔记本也通过同样方式把1935端口打开了；
root@robot:/home/robot/project# ./stream_mpp rtmp://192.168.1.14:1935/live/room1
0: Motion-JPEG
1: YUYV 4:2:2
fmt.w=640,fmt.h=480
fmt.pixfmt=0x56595559
mpp[2766]: mpp_rt: NOT found ion allocator
mpp[2766]: mpp_rt: found drm allocator
mpp[2766]: mpp_info: mpp version: a86f586 author: Herman Chen    2021-02-07 [mpp_enc]: Fix crash on low frame rate case
mpp[2766]: h264e_api_v2: MPP_ENC_SET_PREP_CFG w:h [640:480] stride [640:480]
mpp[2766]: mpp_enc: send header for codec/prep cfg change
mpp[2766]: mpp_enc: mode cbr bps [1500000:2000000:2500000] fps fix [30/1] -> fix [30/1] gop i [60] v [0]
mpp[2766]: mpp_enc: MPP_ENC_SET_RC_CFG bps 2304000 [2160000 : 2448000] fps [30:30] gop 60
mpp[2766]: mpp_enc: send header for rc cfg change rc_mode/fps/gop
mpp[2766]: mpp_enc: mode vbr bps [2160000:2304000:2448000] fps fix [30/1] -> fix [30/1] gop i [60] v [0]
mpp[2766]: mpp_enc: send header for codec/prep cfg change
mpp[2766]: mpp_enc: Please use MPP_ENC_GET_HDR_SYNC instead of unsafe MPP_ENC_GET_EXTRA_INFO
mpp[2766]: mpp_enc: NOTE: MPP_ENC_GET_HDR_SYNC needs MppPacket input
mpp[2766]: vepu_common: warning: stride by bytes 640 is smarller than width 640 mutiple by pixel size 2
mpp[2766]: vepu_common: multiple stride 640 by pixel size 2 and set new byte stride to 1280
encoded frame 0 size 247850
encoded frame 1 size 251245
encoded frame 2 size 250063
encoded frame 3 size 250004
encoded frame 4 size 250358
encoded frame 5 size 250318
encoded frame 6 size 248290
encoded frame 7 size 249243
encoded frame 8 size 248416
encoded frame 9 size 246272
encoded frame 10 size 246575
encoded frame 11 size 247047
encoded frame 12 size 244594
encoded frame 13 size 243950
encoded frame 14 size 244724
encoded frame 15 size 244373
encoded frame 16 size 241648
encoded frame 17 size 242879
encoded frame 18 size 243197
encoded frame 19 size 239016
encoded frame 20 size 241297
encoded frame 21 size 240495
encoded frame 22 size 237950
encoded frame 23 size 237786
encoded frame 24 size 239453
encoded frame 25 size 238489
encoded frame 26 size 236515
encoded frame 27 size 236206
encoded frame 28 size 235704
encoded frame 29 size 237114
[h264 @ 0x28636a00] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, h264, from '/home/robot/project/output.h264':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (Constrained Baseline), yuv420p, 640x480, 30 fps, 30 tbr, 1200k tbn, 60 tbc
Output #0, flv, to 'rtmp://192.168.1.14:1935/live/room1':
    Stream #0:0: Video: h264, yuv420p, 640x480, q=2-31, 60 tbc
RTMP_Connect0, failed to connect socket. 111 (Connection refused)
encode max 30 framesCould not open output URL 'rtmp://192.168.1.14:1935/live/room1'Error occurred.
Segmentation fault (core dumped)

希望得到解惑，不胜感激；问题出在哪？下一步该怎么做？谢谢～～

**Comment by wangluolaowu** [comment]
问题已解决；在rk3399上安装nginx，开启nginx服务；即可实现正常的推流；命令如下： ./stream_mpp rtmp://192.168.1.12:1935/live/room1  其中（192.168.1.12为rk3399地址）；
但新的问题出现了，在和rk3399一个局域网内，在笔记本电脑上通过vlc查看实时视频流；画面大部分时间是灰的，不知道是什么原因；

**Comment by DevoutPrayer** [comment]
尝试使用ffplay或者PotPlayer打开------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;wangluolaowu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月3日(星期三) 晚上6:23
收件人:&nbsp;&quot;DevoutPrayer/streamer&quot;<streamer@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [DevoutPrayer/streamer] RTMP_Connect0, failed to connect socket. 111 (Connection refused) (#2)
