### ISSUE TITLE
尝试使用ffplay或者PotPlayer打开------------------&nbsp;原始邮件&nbsp;------------------

### ISSUE THREAD

**Issue by wangluolaowu** [DevoutPrayer/streamer#3]
您好：
我利用ffplay(linux下命令：sudo ffplay rtmp://192.168.1.12:1935/live/room1 )或者PotPlayer(windows下播放器，输入地址即可)；
二者都有卡顿的现象，但还是有些区别，具体如下：
1.利用linux下ffplay进行播放，刚开始视频流虽然卡顿，但画面还在变化，但大概2分钟左右，后面画面就静止了，估计流被卡死了；
2.利用windows下PotPlayer播放器进行播放，视频流一直有卡顿现象，但画面还是活动变化的；没有出现卡死的现象；

我想问下博主，你当时在firelyrk3399上测试验证的时候（通过wifi进行数据传输），视频流的流畅度如何？怎样才能做到视频流畅，不卡顿（至少15帧/秒的播放速度）？

**Comment by DevoutPrayer** [comment]
我们当时测试是在5GWifi下测试的，没有出现这种情况
你可以先用ffprobe查看流信息，核实是否正确。如果与推流端匹配查看一下网络带宽是否到达正常速度。
如果确实由网络问题导致的，又无法改变网络环境，可以通过更改mpp编码比特率来降低网络带宽占用。
