### ISSUE TITLE
usb摄像头推流后用ffplay播放画面卡顿掉帧和有两个画面

### ISSUE THREAD

**Issue by Csf-mycount** [DevoutPrayer/streamer#7]
![image](https://user-images.githubusercontent.com/56286003/157161862-af9d1934-4ca0-47b0-aca4-f81e11155721.png)

**Comment by Csf-mycount** [comment]
# ./streamer /dev/video0 "rtmp://xstrive.com:21935/live/456"
open_device successful
set IO_METHOD_MMAP
0: Motion-JPEG
1: YUYV 4:2:2
fmt.w=640,fmt.h=480
fmt.pixfmt=0x56595559
init_mmap successful
start init_mpp 
mpp[2255]: mpp_rt: NOT found ion allocator
mpp[2255]: mpp_rt: found drm allocator
mpp[2255]: mpp_info: mpp version: unknown mpp version for missing VCS info
mpp[2255]: h264e_api_v2: MPP_ENC_SET_PREP_CFG w:h [640:480] stride [640:480]
mpp[2255]: mpp_enc: send header for codec/prep cfg change
mpp[2255]: mpp_enc: mode vbr bps [1500000:2000000:2500000] fps fix [30/1] -> fix [30/1] gop i [60] v [0]
mpp[2255]: mpp_enc: MPP_ENC_SET_RC_CFG bps 1920000 [1800000 : 2040000] fps [25:25] gop 60
mpp[2255]: mpp_enc: send header for rc cfg change rc_mode/fps/gop
mpp[2255]: mpp_enc: mode cbr bps [1800000:1920000:2040000] fps fix [25/1] -> fix [25/1] gop i [60] v [0]
set MPP_ENC_H264_CFG_CHANGE_ENTROPY 
mpp[2255]: mpp_enc: send header for codec/prep cfg change
init_mpp successful 
start_capturing 0
start_capturing 1
start_capturing 2
start_capturing 3
mpp[2255]: mpp_enc: Please use MPP_ENC_GET_HDR_SYNC instead of unsafe MPP_ENC_GET_EXTRA_INFO
mpp[2255]: mpp_enc: NOTE: MPP_ENC_GET_HDR_SYNC needs MppPacket input
write_header
AVCodecContext init
Output #0, flv, to 'rtmp://xstrive.com:21935/live/456':
    Stream #0:0: Unknown: none
[flv @ 0x74b0e20] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
------------sendok!
encoded frame 0 size 192410
------------sendok!
encoded frame 1 size 191961
------------sendok!
encoded frame 2 size 194102
------------sendok!
encoded frame 3 size 193869
------------sendok!
encoded frame 4 size 194109
------------sendok!
encoded frame 5 size 196768

**Comment by Csf-mycount** [comment]
请问知道这是什么原因吗 我换了几种播放器都是一样的结果

**Comment by DevoutPrayer** [comment]
不知道问题是否已经解决，可以尝试检查分辨率以及格式是否与摄像头输出一致。
