### ISSUE TITLE
AVPacket没有dts和pts。在vlc或者ffmpeg中无法正常播放视频流

### ISSUE THREAD

**Issue by Pi-Boss** [DevoutPrayer/streamer#9]
从代码中观察AVPacket没有dts和pts。在vlc或者ffmpeg中无法正常播放视频流。
使用mpp_packet_get_pts和mpp_packet_get_dts获取的始终是0
@DevoutPrayer

**Comment by DevoutPrayer** [comment]
dts和pts的计算确实有问题，可以使用PotPlayer或者ffplay播放。
